# This is a basic workflow to help you get started with Actions

name: electron rebuild 

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      electron_version:
        description: 'Electron version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: yarn install
        run: yarn install

      - name: rebuild
        run: npx electron-rebuild -v "${{ github.event.inputs.electron_version }}"
        
      - name: list folder
        run: ls -R node_modules/sqlite3/bin
